In [1]:
import pandas as pd

In [21]:
df = pd.read_csv("human_ebi.txt", sep="\t", low_memory=False)
df = df[df["library_strategy"] == 'WGS']

In [6]:
df.library_strategy.value_counts()

library_strategy
WGS    21750
Name: count, dtype: int64

In [24]:
# Function to split the fastp_ftp into PE1, PE2, and SE columns
df = pd.read_csv("human_ebi.txt", sep="\t", low_memory=False)
df = df[df["library_strategy"] == 'WGS']
df['PE1'] = df['fastq_ftp'].apply(lambda x: x.split(';')[0] if isinstance(x, str) else None)
df['PE2'] = df['fastq_ftp'].apply(lambda x: x.split(';')[1] if isinstance(x, str) and ';' in x else None)
df['SE'] = df['fastq_ftp'].apply(lambda x: isinstance(x, str) and ';' not in x)
SE = df[df['SE'] == True][['run_accession', 'PE1']]
PE = df[df['SE'] == False][['run_accession', 'PE1', 'PE2']]

In [27]:
df = df[['run_accession', 'PE1', 'PE2', 'SE']]

In [30]:
SE = df[df['SE'] == True][['run_accession', 'PE1']]
PE = df[df['SE'] == False][['run_accession', 'PE1', 'PE2']]

In [31]:
SE

      run_accession                                                PE1
105       ERR019089  ftp.sra.ebi.ac.uk/vol1/fastq/ERR019/ERR019089/...
119     ERR10220107  ftp.sra.ebi.ac.uk/vol1/fastq/ERR102/007/ERR102...
1070    ERR13110292  ftp.sra.ebi.ac.uk/vol1/fastq/ERR131/092/ERR131...
1071    ERR13110295  ftp.sra.ebi.ac.uk/vol1/fastq/ERR131/095/ERR131...
1072    ERR13110296  ftp.sra.ebi.ac.uk/vol1/fastq/ERR131/096/ERR131...
...             ...                                                ...
49779    SRR9392065  ftp.sra.ebi.ac.uk/vol1/fastq/SRR939/005/SRR939...
49780    SRR9392070  ftp.sra.ebi.ac.uk/vol1/fastq/SRR939/000/SRR939...
49781    SRR9392083  ftp.sra.ebi.ac.uk/vol1/fastq/SRR939/003/SRR939...
49782    SRR9392085  ftp.sra.ebi.ac.uk/vol1/fastq/SRR939/005/SRR939...
49783    SRR9392088  ftp.sra.ebi.ac.uk/vol1/fastq/SRR939/008/SRR939...

[1324 rows x 2 columns]

In [32]:
df = pd.read_csv("/group/ctbrowngrp4/2024-mhussien-QC/zebrafish/data/zebrafish_ena.tsv", sep="\t", low_memory=False)

In [33]:
df

,run_accession,experiment_title,fastq_ftp,library_strategy,library_source,library_selection,instrument_platform,last_updated,read_count
0,DRR029940,Illumina HiSeq 2500 sequencing: Illumina HiSeq...,ftp.sra.ebi.ac.uk/vol1/fastq/DRR029/DRR029940/...,RNA-Seq,TRANSCRIPTOMIC,cDNA,ILLUMINA,2019-01-27,18295876
1,DRR032730,Illumina HiSeq 2000 sequencing: Illumina HiSeq...,ftp.sra.ebi.ac.uk/vol1/fastq/DRR032/DRR032730/...,RNA-Seq,TRANSCRIPTOMIC,other,ILLUMINA,2019-11-09,37443860
2,DRR032733,Illumina HiSeq 2000 sequencing: Illumina HiSeq...,ftp.sra.ebi.ac.uk/vol1/fastq/DRR032/DRR032733/...,RNA-Seq,TRANSCRIPTOMIC,other,ILLUMINA,2020-09-29,41566511
3,DRR032734,Illumina HiSeq 2000 sequencing: Illumina HiSeq...,ftp.sra.ebi.ac.uk/vol1/fastq/DRR032/DRR032734/...,RNA-Seq,TRANSCRIPTOMIC,other,ILLUMINA,2020-09-29,36875170
4,DRR032735,Illumina HiSeq 2000 sequencing: Illumina HiSeq...,ftp.sra.ebi.ac.uk/vol1/fastq/DRR032/DRR032735/...,RNA-Seq,TRANSCRIPTOMIC,other,ILLUMINA,2020-09-29,43102197
...,...,...,...,...,...,...,...,...,...
151009,SRR998907,Illumina HiSeq 2000 sequencing: GSM1236412: MZ...,ftp.sra.ebi.ac.uk/vol1/fastq/SRR998/SRR998907/...,RNA-Seq,TRANSCRIPTOMIC,cDNA,ILLUMINA,2020-05-24,4000000
151010,SRR998908,Illumina HiSeq 2000 sequencing: GSM1236412: MZ...,ftp.sra.ebi.ac.uk/vol1/fastq/SRR998/SRR998908/...,RNA-Seq,TRANSCRIPTOMIC,cDNA,ILLUMINA,2020-05-25,3702972
151011,SRR998913,Illumina HiSeq 2000 sequencing: GSM1236413: MZ...,ftp.sra.ebi.ac.uk/vol1/fastq/SRR998/SRR998913/...,RNA-Seq,TRANSCRIPTOMIC,cDNA,ILLUMINA,2019-10-23,4000000
151012,SRR998915,Illumina HiSeq 2000 sequencing: GSM1236413: MZ...,ftp.sra.ebi.ac.uk/vol1/fastq/SRR998/SRR998915/...,RNA-Seq,TRANSCRIPTOMIC,cDNA,ILLUMINA,2020-05-24,4000000
151013,SRR998923,Illumina HiSeq 2000 sequencing: GSM1236414: MZ...,ftp.sra.ebi.ac.uk/vol1/fastq/SRR998/SRR998923/...,RNA-Seq,TRANSCRIPTOMIC,cDNA,ILLUMINA,2019-11-01,4000000